# properties
title: ntSystems | info.tech
email: postmaster@ntSystems.it
description: by Daniel Nitz and Thomas Torggler
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.tomt.it" # the base hostname & protocol for your site
twitter_username: ntSystemsit
github_username:  tomtorggler
disqus_username: ntsystems

# settings
markdown: kramdown
theme: minima