title: ntSystems | info.tech
email: blog@ntsystems.it
description: "by Daniel Nitz and Thomas Torggler."
baseurl: "" 
url: "https://ntsystems.it" 
disqus_username: ntsystems
twitter_username: ntsystemsit
github_username:  tomtorggler
timezone: Europe/Rome

# Build settings
markdown: kramdown
theme: minima
paginate: 10
permalink: /post/:title

jquery: 2.2.2

gems:
  - jekyll-redirect-from
  - jekyll-paginate

# Default Values for "Front Matter"
defaults:
  -
    scope:
      path: ""
    values:
      excerpt_separator: <!-- more -->
  -
    scope:
      path: "_posts/PowerShell"
    values:
      permalink: "/PowerShell/:title/"
      excerpt_separator: <!-- more -->