# properties
title: blog.tomt.it
email: tom@uclab.eu
description: this is just another blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.tomt.it" # the base hostname & protocol for your site
twitter_username: torggler
github_username:  tomtorggler

# settings
markdown: kramdown
theme: minima