# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ntSystems | info.tech
email: blog@ntsystems.it
description: > # this means to ignore newlines until "baseurl:"
  by Daniel Nitz and Thomas Torggler.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ntsystems.it" # the base hostname & protocol for your site
disqus_username: ntsystems
twitter_username: ntsystemsit
github_username:  tomtorggler

# Build settings
markdown: kramdown
theme: minima
paginate: 10
permalink: /post/:title

gems:
  - algoliasearch-jekyll
  - jekyll-redirect-from
algolia:
  application_id: 'JPAVBSA8D9'
  index_name: 'ntsystems'
  read_only_api_key: 'd2c7c639fc2961e6fd5b6033ea22b978'
  record_css_selector: 'p,ul,code'
  excluded_files:
    - index.html